"use client";

import { useEffect, useState } from "react";
import { Loader2 } from "lucide-react";

/**
 * Renders one of the static legal HTML documents that live in /public.
 * Used by both the standalone /terms and /privacy pages and the in-flow modal
 * during onboarding, so the styling stays in one place.
 *
 * The HTML is generated by an external service (TermsFeed-style) and tags
 * elements with `data-custom-class` attributes — the `:global()` rules below
 * target those.
 */
export function LegalContent({ source }: { source: string }) {
  const [html, setHtml] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    setHtml(null);
    setError(null);

    fetch(source)
      .then((response) => {
        if (!response.ok) throw new Error(`HTTP ${response.status}`);
        return response.text();
      })
      .then((text) => {
        if (!cancelled) setHtml(text);
      })
      .catch((err) => {
        if (!cancelled) setError(err instanceof Error ? err.message : "Failed to load");
      });

    return () => {
      cancelled = true;
    };
  }, [source]);

  if (error) {
    return (
      <p style={{ color: "var(--color-text-secondary)", fontSize: 14 }}>
        Couldn&apos;t load this document. Please try again later.
      </p>
    );
  }

  if (html === null) {
    return (
      <div
        style={{
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          padding: 48,
        }}
      >
        <Loader2
          size={24}
          className="animate-spin"
          style={{ color: "var(--color-text-muted)" }}
        />
      </div>
    );
  }

  return (
    <>
      <div
        className="legal-content"
        dangerouslySetInnerHTML={{ __html: html }}
        style={{ lineHeight: 1.6 }}
      />

      <style jsx>{`
        .legal-content :global([data-custom-class="title"]),
        .legal-content :global([data-custom-class="title"] *) {
          color: var(--color-text) !important;
          font-family: var(--font-family) !important;
          font-size: 32px !important;
          font-weight: 700 !important;
          margin-bottom: 16px !important;
        }

        .legal-content :global([data-custom-class="subtitle"]),
        .legal-content :global([data-custom-class="subtitle"] *) {
          color: var(--color-text-secondary) !important;
          font-family: var(--font-family) !important;
          font-size: 14px !important;
          margin-bottom: 32px !important;
        }

        .legal-content :global([data-custom-class="heading_1"]),
        .legal-content :global([data-custom-class="heading_1"] *),
        .legal-content :global(h1) {
          color: var(--color-text) !important;
          font-family: var(--font-family) !important;
          font-size: 24px !important;
          font-weight: 600 !important;
          margin-top: 32px !important;
          margin-bottom: 16px !important;
        }

        .legal-content :global([data-custom-class="heading_2"]),
        .legal-content :global([data-custom-class="heading_2"] *),
        .legal-content :global(h2) {
          color: var(--color-text) !important;
          font-family: var(--font-family) !important;
          font-size: 20px !important;
          font-weight: 600 !important;
          margin-top: 24px !important;
          margin-bottom: 12px !important;
        }

        .legal-content :global([data-custom-class="body_text"]),
        .legal-content :global([data-custom-class="body_text"] *),
        .legal-content :global(p),
        .legal-content :global(li),
        .legal-content :global(span) {
          color: var(--color-text-secondary) !important;
          font-family: var(--font-family) !important;
          font-size: 14px !important;
          line-height: 1.6 !important;
        }

        .legal-content :global([data-custom-class="link"]),
        .legal-content :global([data-custom-class="link"] *),
        .legal-content :global(a) {
          color: var(--color-tint) !important;
          font-family: var(--font-family) !important;
          font-size: 14px !important;
          text-decoration: underline !important;
        }

        .legal-content :global(a:hover) {
          color: var(--color-tint-hover) !important;
        }

        .legal-content :global(ul),
        .legal-content :global(ol) {
          padding-left: 24px !important;
          margin: 16px 0 !important;
        }

        .legal-content :global(li) {
          margin-bottom: 8px !important;
        }

        .legal-content :global(table) {
          width: 100% !important;
          border-collapse: collapse !important;
          margin: 24px 0 !important;
        }

        .legal-content :global(td),
        .legal-content :global(th) {
          border: 1px solid var(--color-border-subtle) !important;
          padding: 12px !important;
          color: var(--color-text-secondary) !important;
        }

        .legal-content :global(th) {
          background-color: var(--color-background-muted) !important;
          color: var(--color-text) !important;
          font-weight: 600 !important;
        }

        .legal-content :global(.MsoNormal) {
          margin: 8px 0 !important;
        }

        @media (max-width: 768px) {
          .legal-content :global([data-custom-class="title"]),
          .legal-content :global([data-custom-class="title"] *) {
            font-size: 24px !important;
          }

          .legal-content :global([data-custom-class="heading_1"]),
          .legal-content :global([data-custom-class="heading_1"] *),
          .legal-content :global(h1) {
            font-size: 20px !important;
          }

          .legal-content :global([data-custom-class="heading_2"]),
          .legal-content :global([data-custom-class="heading_2"] *),
          .legal-content :global(h2) {
            font-size: 18px !important;
          }
        }
      `}</style>
    </>
  );
}
